### ISSUE TITLE
Issue with the Resource API regions.

### ISSUE THREAD

**Issue by readingdancer** [Vizioz/CovidSupport#20]
Hi @MiguelLopez6 ,

Could you please check the API:

/resource/settings

The regions seem to be pulling from the content field which I think is currently a text field? However, it should really be pulled from the list within the Regions section ( for the current site ).

![regions](https://user-images.githubusercontent.com/4398217/85813621-afdd0700-b731-11ea-9d28-4e828b039be9.jpg)

Currently this is showing:

``` 
  "regions": [
    "orange_county",
    "chatham_county",
    "harnett_county",
    "durham_county",
    "person_county",
    "alamance_county",
    "wake_county",
    "granville_county",
    "guilford_county",
    "caswell_county",
    "pearson_county",
    "Chatham",
    "Orange",
    "Durham",
    "Lee",
    "Alamance",
    "Moore"
  ]
```

This is clearly not a large enough list for the data in our system, however for now, it's probably what we want to show on the site, clearly if we add more, the additional items would them be found in their own area, otherwise they would only be found when searching All NC.

I also think it would be really helpful if you can pass an ID that we then use to pass back to the API calls to filter the data returned.

So when these changes are made, I'd like to see the following format:

``` 
  "regions": [
    {"name": "All NC", "id": "1"},
    {"name": "Chatham County", "id": "2"},
    {"name": "Durham County", "id": "3"},
    {"name": "Orange County", "id": "4"},
    {"name": "Wake County", "id": "5"}
]
```

Note: The ID's would need to be from the item within Umbraco, the numbers above were just for demonstration.

Thanks, Chris

**Comment by MiguelLopez6** [comment]
Currently pulling from the "County" property of resources, as the regions node was created after the social services. At some point, we might need to change the county property of other resources to be a region picker too.

**Comment by readingdancer** [comment]
Hi Miguel,

Now is the time to do that, which is why I raised this ticket :)

If you create the additional property, if you cannot update it programmatically we can always get some people to help update it via the CMS.

All the other resources just need to be a single picker, rather than a multiple one.

Cheers, Chris

**Comment by readingdancer** [comment]
FYI, I am fine with the ID being the Umbraco "slug" for the content item... i.e., for `Chatham County` it's probably  `chathamcounty` as that would probably aid us in debugging issues. Clearly the importance is you are able to search using either the ID or this "slug" so if the second is going to make the search harder, then stick with the ID.

**Comment by MiguelLopez6** [comment]
There are a lot of records to update them manually...

**Comment by MiguelLopez6** [comment]
Using the int ID is easier for searching, obviously.

**Comment by MiguelLopez6** [comment]
This is now returning the regions from the Regions node.

**Comment by MiguelLopez6** [comment]
The API method "getByRegion" works now with both the id and the slug.
The regions now are like {"name": "Chatham County", "id": "2", slug: "chatham-county"}, the slug taking the url name of the node. 
I think "slug" should be renamed to something more appropriate, maybe "id-name" or "url-name"...

**Comment by MiguelLopez6** [comment]
I have written the code to export string regions to region picker data type, which is working locally, but I still get SQL lockout errors. I need to create some error trapping and response summary to identify the successful and unsuccessful nodes.
Maybe it will be a better idea to migrate to SQL before attempting this.

**Comment by readingdancer** [comment]
> The regions now are like {"name": "Chatham County", "id": "2", slug: "chatham-county"}, the slug taking the url name of the node.

I am happy for you to rename it, how about "alias" or "code"

I don't think we need to support two methods of lookup, so I'd prefer it if we remove the id from this API response, you can leave the getByRegion method still working with both, in case we find a reason to need it.

**Comment by MiguelLopez6** [comment]
Get regions as  {"name": "Chatham County", alias: "chatham-county"}
