### ISSUE TITLE
The Categories in the Resources API are not returning correctly.

### ISSUE THREAD

**Issue by readingdancer** [Vizioz/CovidSupport#21]
Currently when requesting the Settings via the API, we get the regions and the following categories (I am not showing the entire list) :
```  
"categories": [
    {
      "id": 1284,
      "name": "Farms and Farmers' Markets",
      "code": "farmsResourceGroup",
      "subcategories": []
    },
    {
      "id": 1285,
      "name": "Food Resources",
      "code": "foodResourceCategoryGroup",
      "subcategories": []
    }, ...
```

Please can you remove the "code" as now the data is within Umbraco, we should be able to use the ID's to reference the relationship to the actual resources, so I think "code" is redundant ( unless I have missed something? ).

Also the sub categories do not seem to be returning anything? As you can see the Food Resources is showing nothing and yet, we definitely have resource categories in those folders as you have uploaded all the data now.

Cheers,

Chris

**Comment by MiguelLopez6** [comment]
The categories in the tree will be those of the content types that are under the groups "Resource Types" and "Resource Category Groups" defined in the settings section.

I thought of 2 approaches. Either this one, or either get all nodes that don't have children (if they don't have children it means they are a resource), but I thought the second one would be more costly. It also might not work if in the future we decide that resources can admit children of some type.

**Comment by readingdancer** [comment]
Hi Miguel,

Sounds fine to me, but as you can see, currently it's not returning what we would expect.

Cheers,

Chris

**Comment by MiguelLopez6** [comment]
I know, I used the first approach, working locally, but still didnt push it.

**Comment by MiguelLopez6** [comment]
Subcategories working properly now.
Still didn't change the way to get them (nodes with a list view), still using content types inside a specific folder.

**Comment by MiguelLopez6** [comment]
Finally, get the category tree from content nodes with list view
