### ISSUE TITLE
Change to the Get Resource API results.

### ISSUE THREAD

**Issue by readingdancer** [Vizioz/CovidSupport#22]
Hi @MiguelLopez6 

The API looks good, I just have a request to make, which is could you please could you change how the times are returned?

Currently you are returning:

```
  "wednesday": "[{\"key\":\"0dc14850-5fc7-455a-8a01-094fce17d1e4\",
\"startTime\":\"0001-01-01 15:00:00\",\"endTime\":\"0001-01-01 18:00:00\",\"ncContentTypeAlias\":\"openingTime\"}]",
```

It would look better like this ( but don't implement this, read on... ):
```
  "wednesday": [{"startTime":"15:00:00","endTime":"18:00:00"}],
```

It looks like you are returning an object within a string, but this should really be part of the JSON data.

### What I'd really like to see
It would be good if these were all grouped inside an "openHours" object and the special hours inside a "specialHours" object so the returned object looked like:

```
  "openHours": [
     {"day" : "wednesday", "hours" : [{"startTime":"15:00:00","endTime":"18:00:00"}] },
     {"day" : "friday", "hours" : [{"startTime":"15:00:00","endTime":"18:00:00"}] },
     {"day" : "sunday", "hours" : [{"startTime":"10:00:00","endTime":"12:00:00"}, {"startTime":"15:00:00","endTime":"18:00:00"}] },
  "specialHours":[ ...
```

This way we should be able to easily access the data in VueJS and cycle through the objects, please also ensure the data is always returned in the correct day order ( Monday to Sunday ).

Thanks, Chris

**Comment by MiguelLopez6** [comment]
Currently returning string as originally they were a textbox.

**Comment by readingdancer** [comment]
Yes, I understand the reason it was like this, but now we have all the data in the format we want in Umbraco, we need to refactor this to make it output more useful JSON data and to remove wasteful content ( the date stuff ).

**Comment by MiguelLopez6** [comment]
This is returning now the requested format for the opening times.
